### ISSUE TITLE
Inconsistent compile sdk version

### ISSUE THREAD

**Issue by oakkub** [RahulRavindren/surveyapp#7]
In module `logic` the compile sdk version is set to `26` while other are set to `27`

![screen shot 2561-10-08 at 17 05 10](https://user-images.githubusercontent.com/9587882/46603126-5cb9bf80-cb1c-11e8-996c-56761ddf198d.png)

And I also noticed that you have an compile sdk version in a root gradle file, but you only use them in `app` module

**Comment by RahulRavindren** [comment]
Fixed. Closing the issue.
